apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: {{ .Values.namespace }} 
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: java-app
        image: {{ .Values.deploy.containerImage }}:{{ .Values.deploy.containerTag }}
        command: ["./mvnw"]
        args: ["spring-boot:run", "-Dspring-boot.run.profiles=mysql"]
        env:
          - name: MYSQL_URL
            value: jdbc:mysql://{{ .Values.deploy.mysqlUrl }}/petclinic
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret 
                key: MYSQL_USER
          - name: MYSQL_PASS
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASS
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: {{ .Values.deploy.dockerSecretName }} 

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30036
