apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.name }}
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.deploy.labels.app }}
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deploy.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.labels.app }}
    spec:
      containers:
      - name: java-app
        image: {{ .Values.deploy.containerImage }}:{{ .Values.deploy.containerTag }}
        command: ["./mvnw"]
        args: ["spring-boot:run", "-Dspring-boot.run.profiles=mysql"]
        env:
          - name: MYSQL_URL
            value: jdbc:mysql://{{ .Values.deploy.mysqlUrl }}/petclinic
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }} 
                key: MYSQL_USER
          - name: MYSQL_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: MYSQL_PASS
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: {{ .Values.deploy.dockerSecretName }}
