apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
data:
  MYSQL_USER: {{ .Values.secret.mysqlUser  | b64enc | quote }} 
  MYSQL_PASS: {{ .Values.secret.mysqlPass  | b64enc | quote }}
