apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.service.labels.app }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
